name: Generate GitHub Metrics

on:
  schedule:
  - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:          # enables manual run button

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: red-robin
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_followup: yes

